name: CI-examples

on:
  push:
    branches: [dev, main]
    paths-ignore:
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install

      - name: Pre build packages
        run: yarn workspaces foreach -W --exclude '@examples/*' --no-private run build

      - name: Typecheck (path aliases)
        run: yarn workspaces foreach -W --from '@examples/*' run typecheck

      - name: Typecheck (no paths aliases)
        run: yarn workspaces foreach -W --from '@examples/*' run typecheck-no-paths

      - name: Lint
        run: yarn workspaces foreach -W --from '@examples/*' run lint

      - name: Build example apps
        run: yarn workspaces foreach -W --from '@examples/*' run build
        env:
          NEXTJS_IGNORE_ESLINT: true
          NEXTJS_IGNORE_TYPECHECK: true
          NEXT_DISABLE_SOURCEMAPS: true
          NEXT_TELEMETRY_DISABLED: true
